use crate::ir::*;

pub struct NativeGenerator;

impl NativeGenerator {
    pub fn generate_c(program: &Program) -> String {
        let mut c = String::new();
        c.push_str("/* Generated by Project ReZero Reversible Compiler */\n");
        c.push_str("#include <stdio.h>\n#include <stdlib.h>\n#include <stdint.h>\n#include <string.h>\n\n");
        c.push_str("typedef struct { char* name; int32_t val; } LRSNode;\n");
        c.push_str("#define LRS_MAX 100000\n");
        c.push_str("LRSNode lrs[LRS_MAX]; int lrs_ptr = 0;\n\n");
        c.push_str("void push_lrs(char* name, int32_t val) { if(lrs_ptr < LRS_MAX) { lrs[lrs_ptr].name = name; lrs[lrs_ptr].val = val; lrs_ptr++; } }\n");
        c.push_str("int32_t pop_lrs(char* name) { for(int i=lrs_ptr-1; i>=0; i--) { if(strcmp(lrs[i].name, name) == 0) return lrs[i].val; } return 0; }\n\n");

        for func in &program.functions {
            let ret_t = match func.ret_ty { Type::Int => "int32_t", Type::Bool => "int8_t", _ => "void*" };
            c.push_str(&format!("{} {}(", ret_t, func.name));
            let params: Vec<String> = func.params.iter().map(|(n, _)| format!("int32_t {}", n)).collect();
            c.push_str(&params.join(", "));
            c.push_str(") {\n");
            for ir in &func.body {
                c.push_str(&Self::gen_ir(ir, 1));
            }
            c.push_str("}\n\n");
        }

        c.push_str("int main(int argc, char** argv) {\n");
        c.push_str("  printf(\"--- ReZero Native Runtime Ready ---\\n\");\n");
        if let Some(f) = program.functions.get(0) {
            c.push_str(&format!("  printf(\"Executing entry: {}()\\n\", \"{}\");\n", f.name, f.name));
            c.push_str(&format!("  int32_t res = {}(10, 20);\n", f.name));
            c.push_str("  printf(\"Result: %d\\n\", res);\n");
        }
        c.push_str("  printf(\"LRS Stack Depth: %d\\n\", lrs_ptr);\n");
        c.push_str("  return 0;\n}\n");
        c
    }

    fn gen_ir(ir: &IR, indent: usize) -> String {
        let sp = "  ".repeat(indent);
        match ir {
            IR::Declare { name, init, .. } => {
                let init_val = if let Some(e) = init { format!(" = {}", Self::gen_expr(e)) } else { "".into() };
                format!("{}int32_t {}{};\n", sp, name, init_val)
            }
            IR::Assign { name, val } => {
                let mut s = format!("{}push_lrs(\"{}\", {});\n", sp, name, name);
                s.push_str(&format!("{}{} = {};\n", sp, name, Self::gen_expr(val)));
                s
            }
            IR::Return(e) => format!("{}return {};\n", sp, Self::gen_expr(e)),
            IR::If { cond, then_b, else_b } => {
                let mut s = format!("{}if ({}) {{\n", sp, Self::gen_expr(cond));
                for i in then_b { s.push_str(&Self::gen_ir(i, indent + 1)); }
                s.push_str(&format!("{}}} else {{\n", sp));
                for i in else_b { s.push_str(&Self::gen_ir(i, indent + 1)); }
                s.push_str(&format!("{}}}\n", sp));
                s
            }
            IR::PushLRS { name, .. } => format!("{}push_lrs(\"{}\", {});\n", sp, name, name),
            _ => "".into(),
        }
    }

    fn gen_expr(expr: &Expr) -> String {
        match expr {
            Expr::Literal(v) => v.to_string(),
            Expr::Variable(n) => n.clone(),
            Expr::Binary { op, left, right } => {
                let o = match op { Op::Add => "+", Op::Sub => "-", Op::Mul => "*", Op::Div => "/" };
                format!("({} {} {})", Self::gen_expr(left), o, Self::gen_expr(right))
            }
            Expr::Compare { op, left, right } => {
                let o = match op { CompOp::Gt => ">", CompOp::Ge => ">=", CompOp::Lt => "<", CompOp::Le => "<=", CompOp::Eq => "==", CompOp::Ne => "!=" };
                format!("({} {} {})", Self::gen_expr(left), o, Self::gen_expr(right))
            }
            Expr::ArrayAccess { name, index } => format!("{}[{}]", name, Self::gen_expr(index)),
            Expr::PointerDereference(name) => format!("(*{})", name),
        }
    }
}
